### ISSUE TITLE
Getting crash not everytime but some users ScratchableLayoutDrawer.createBitmapFromScratchableView

### ISSUE THREAD

**Issue by gauravpay** [jackpocket/android-scratchoff#19]
Fatal Exception: java.lang.IllegalArgumentException
width and height must be > 0
android.graphics.Bitmap.createBitmap (Bitmap.java:1138)

android.graphics.Bitmap.createBitmap (Bitmap.java:1016)
com.jackpocket.scratchoff.ScratchableLayoutDrawer.createBitmapFromScratchableView (ScratchableLayoutDrawer.java:178)
com.jackpocket.scratchoff.ScratchableLayoutDrawer.initializeLaidOutScratchableView (ScratchableLayoutDrawer.java:155)
com.jackpocket.scratchoff.ScratchableLayoutDrawer$2.run (ScratchableLayoutDrawer.java:148)
com.jackpocket.scratchoff.ScratchableLayoutDrawer$3.onGlobalLayout (ScratchableLayoutDrawer.java:353)
android.view.ViewTreeObserver.dispatchOnGlobalLayout (ViewTreeObserver.java:1079)

**Comment by mattsilber** [comment]
👋 sorry for the late response; this slipped by me. Are there any specific devices or OS versions this appears to be happening on? 

Generally the view should have been both measured and laid out when `initializeLaidOutScratchableView` is called, which signals our ability to create the scratchable surface area (in `createBitmapFromScratchableView`). If that is no longer always the case, we may have to re-evaluate that initial setup

**Comment by mattsilber** [comment]
Reopening this issue, as the `OnPreDrawListener` usage will cause the same error on Samsung (Android 14) devices somewhere around the Activity-restoration process. I have not yet reproduced it, but the root cause appears to be the same: the listener is being called without a valid width/height value.

Looking at the implications of letting the `OnPreDrawListener` live longer than a single call
